### ISSUE TITLE
세부기능 삭제 menu3-4올릴게요

### ISSUE THREAD

**Issue by jooe0824** [KimKimLee/swgHW#11]
delete하는 세부 기능 올릴게요 아직 interface완벽히 안되었구요 
menu 3-3 은 이번주 내로 올리겠습니다.
delete하는 기능 비슷해서 menu1,2에서도 비슷하게 해도 될것 같네요..

**Comment by Kimgakim** [comment]
넵 전 그것 참고해서 올리겠습니당

**Comment by jooe0824** [comment]
올렸습니다 close it!!!!!!
