### ISSUE TITLE
getter setter 관련 질문 

### ISSUE THREAD

**Issue by jooe0824** [KimKimLee/swgHW#8]
모든 메뉴마다 getter setter가 있어야 편리 할 것 같아서 miguell님이 올리신 코드에 이미 있는 코드만 따서 따로 올려 놓겠습니다. 
각자 필요한 변수명만 잘 바꾸면 사용하기 편리할듯요~~
오늘도 have a good day LOL!!
@miguellll  @Kimgakim

**Comment by Kimgakim** [comment]
넹~~ 우리 자신 화이팅~~

**Comment by miguellll** [comment]
넹!

**Comment by jooe0824** [comment]
finish~~~~~~

**Comment by jooe0824** [comment]
close하겠슴
